Change path for missing headers of some progs/*.c
Previously:

for DEPS in `echo *.c */*.c`; do \
gcc -I. -I /usr/src/gpm-1.20.7/src -M  -I/usr/src/gpm-1.20.7/src -DHAVE_CONFIG_H -include headers/config.h -Wall -DSYSCONFDIR="\"/etc\"" -DSBINDIR="\"/usr/sbin\"" -D_GNU_SOURCE  $DEPS | \
/bin/sed 's/^\(.*\)\.o\([ :]+\)/\1.o \1.lo\2/g' >> .depend ; done
prog/display-buttons.c:39:57: fatal error: gpm.h: No such file or directory
 #include <gpm.h>              /* gpm information      */
                                                         ^
compilation terminated.
prog/display-coords.c:40:57: fatal error: gpm.h: No such file or directory
 #include <gpm.h>              /* gpm information      */
                                                         ^
compilation terminated.
prog/get-versions.c:25:57: fatal error: gpm.h: No such file or directory
 #include <gpm.h>              /* gpm information      */
                                                         ^
compilation terminated.